contracts: prevent hoisting of hardhat-deploy-ethers
Without this patch, test/claimable.test.ts fails with:

    test/claimable.test.ts:13:10 - error TS2322: Type 'import("/home/adam/blockchain/Panther/git/zkp-staking/node_modules/@nomiclabs/hardhat-ethers/signers"
    ).SignerWithAddress' is not assignable to type 'import("/home/adam/blockchain/Panther/git/zkp-staking/contracts/node_modules/@nomiclabs/hardhat-ethers/dist/src/signers").SignerWithAddress'.
      Types have separate declarations of a private property '_signer'.

    13         [user] = await ethers.getSigners();
                ~~~~

"yarn why" shows the issue in more detail.

    % yarn why @nomiclabs/hardhat-ethers
    yarn why v1.22.15
    [1/4] Why do we have the module "@nomiclabs/hardhat-ethers"...?
    [2/4] Initialising dependency graph...
    [3/4] Finding dependency...
    [4/4] Calculating file sizes...
    => Found "@nomiclabs/hardhat-ethers@0.3.0-beta.13"
    info Reasons this module exists
       - "_project_#@zkp-staking#contracts" depends on it
       - Hoisted from "_project_#@zkp-staking#contracts#@nomiclabs#hardhat-ethers"
    info Disk size without dependencies: "280KB"
    info Disk size with unique dependencies: "280KB"
    info Disk size with transitive dependencies: "280KB"
    info Number of shared dependencies: 0
    => Found "@zkp-staking/contracts#@nomiclabs/hardhat-ethers@0.3.0-beta.12"
    info This module exists because "_project_#@zkp-staking#contracts" depends on it.
    info Disk size without dependencies: "400KB"
    info Disk size with unique dependencies: "400KB"
    info Disk size with transitive dependencies: "400KB"
    info Number of shared dependencies: 0
    Done in 1.18s.

It's not clear from this why both are present, but preventing hoisting
prevents this duplicate installation.